#!/bin/bash

alias git="hub"
alias pt="pt --global-gitignore --ignore=tags"

alias dce="docker-compose exec"
alias dcu="docker-compose up -d"
alias dct="docker-compose -f docker-compose.test.yml up"

