#!/bin/bash

alias pt="pt --global-gitignore --ignore=tags"

alias dce="docker-compose exec"
alias dcu="docker-compose up -d"
alias dct="docker-compose -f docker-compose.test.yml run test"
alias dcr="docker-compose run"
alias dcb="docker-compose build"
function dcd {
    docker-compose $@ down
}

alias pt="pt --global-gitignore --ignore=tags"
alias vim="nvim"

alias xclip="xclip -selection clipboard"

# Git aliases
alias gch="git diff --name-only --cached --diff-filter=MRA"
alias gfb='git checkout $(git branch | fzf)'

# Helpers
alias pcsf="php-cs-fixer fix --config .php-cs-fixer.dist.php \$(gch | grep '\.php\$') --verbose"

if [ -x "$(command -v lstr)" ]
then 
    alias tree="lstr --icons"
fi
